### PR TITLE
Fix for missing stub files Issue #120

### LINKED ISSUE #120: Python Stubs missing from build
When the library is installed from PYPI it doesn't ship the *.pyi files. This prevents downstream packages and IDE's unable to find the  type definitions in the [src/_internal/dynamic.pyi ](https://github.com/wenkokke/py-tree-sitter-talon/blob/dev/src/tree_sitter_talon/_internal/dynamic.pyi) 

This can be fixed by modifying the pyproject.toml to include all .pyi files in the src folder as package data. 
https://setuptools.pypa.io/en/latest/userguide/datafiles.html#package-data

### PR DESCRIPTION
**Pull request by Nova38**
Fix #120:

This should included the pyi files in the pypi package. I tested it locally with `pip install -v ." and then launched vscode in the talonfmt repo and it was able to retrive the types that where in the dynamic.pyi instead of just resolving them to unknown

### CODE REVIEW

**Comment by Nova38** [comment]
I found all of the statements to add to the allow list by running the output of the tox tests through the following python snippet.

```python
ver = ["pre","3.7","3.8", "3.9", "3.10", "3.11"]
lines = text.split("============================= test session starts ==============================")
ver_lines = {v:text for v,text in zip(ver, lines) if "FAIL" in text}
ver_errors = {v:re.findall(r"error: .*", text) for v,text in ver_lines.items()}
ver_lines_to_add_allow = {v:[text.split("error: ")[1].split(" ")[0] for text in lines] for v, lines in ver_errors.items()}

```

**Comment by wenkokke** [comment]
This is a recent bug in mypy, see:
https://github.com/python/mypy/pull/15689

Therefore, I besid believe the right solution isn't to add these to the ignore files, but to restrict the mypy version to exclude the broken versions.

**Comment by wenkokke** [comment]
This fix appears to have been published in version 1.5. Can you confirm your mypy version?

**Comment by Nova38** [comment]
It looks like the mypy that is running in the CI is 1.5.0 in the output of the pip freeze.

**Comment by wenkokke** [comment]
Okay, let's just merge this for now, then :)

**Pull request merged**
